server:
  port: 18080

rocketmq:
  name-server: localhost:9876
  producer:
    group: my-group1
  pull-consumer:
    group: my_consumer1
    topic: normalTopic
    selector-type: TAG
    selector-expression: tag_0
  consumer:
    topic: TopicTest
    group: TopicGroup
  demo:
    topic: TopicTest
